openapi: 3.0.0
info:
  title: Employee Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /employees:
    post:
      summary: Создание сотрудника
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
            examples:
              EmployeeWithPassport:
                value:
                  name: "John"
                  surname: "Doe"
                  phone: "123456789"
                  company_id: 1
                  department_id: 1
                  passport:
                    type: "Passport"
                    number: "A12345678"
              EmployeeWithoutPassport:
                value:
                  name: "John"
                  surname: "Doe"
                  phone: "123456789"
                  company_id: 1
                  department_id: 1
      responses:
        '201':
          description: Сотрудник успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
  /employees/{id}:
    delete:
      summary: Удаление сотрудника по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Employee deleted successfully
    put:
      summary: Обновление данных о сутруднике по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
            examples:
              Employee:
                value:
                  name: "John"
                  surname: "Doe"
                  phone: "123456789"
                  company_id: 1
                  department_id: 1
      responses:
        '204':
          description: Данные сотрудника обновлены
  /companies/{company_id}/employees:
    get:
      summary: Получение списка сотрудников по ID компании
      parameters:
        - name: company_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список сотрудников
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
  /departments/{department_id}/employees:
    get:
      summary: Получение списка сотрудников по ID отдела
      parameters:
        - name: department_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список сотрудников
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        surname:
          type: string
        phone:
          type: string
        company_id:
          type: integer
        department_id:
          type: integer
        passport:
          type: object
          properties:
            type:
              type: string
            number:
              type: string
      required:
        - name
        - surname
        - phone
        - company_id
        - department_id